name: Build

on:
  push:
    branches:
      - master
      - dev

env:
  DOCKERHUB_USERNAME: apptality
  REGISTRY_IMAGE: apptality/aws-ecs-cloudmap-prometheus-discovery

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract GitVersion variables
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:${{ steps.gitversion.outputs.fullSemVer }}

#      - name: Build and push Docker images (Linux)
#        run: |
#          DOCKER_ORG_NAME=${DOCKER_ORG_NAME:-apptality}
#          DOCKER_APP_NAME=${APP_NAME:-aws-ecs-cloudmap-prometheus-discovery}
#          DOCKER_IMAGE_NAME="${DOCKER_ORG_NAME}/${DOCKER_APP_NAME}"
#          DOCKER_IMAGE_TAG=${{ steps.gitversion.outputs.fullSemVer }}
#          DOCKER_IMAGE="${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
#          echo "Building and pushing ${DOCKER_IMAGE}"
#          docker buildx build --file Dockerfile --platform linux/amd64,linux/arm64 --tag $DOCKER_IMAGE --push .
#          # docker tag $IMAGE_NAME:$DOCKER_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE
#          # docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE
